<mvc:View
    controllerName="{{NAMESPACE}}.controller.{{VIEW}}"
    displayBlock="true"
    xmlns="sap.m"
    xmlns:mvc="sap.ui.core.mvc"
    xmlns:core="sap.ui.core"
>
    <Page
        id="{{VIEW}}"
        showHeader="false"
    >
        <content>
            <Text text="Generated by UI5 Ultima" />
        </content>
    </Page>
</mvc:View>